# Generated by Django 2.2.4 on 2019-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190903_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='none.jpg', upload_to='movie_pics'),
        ),
    ]
